// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlrdqdmluhphupkmflpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZscmRxZG1sdWhwaHVwa21mbHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzI1NjQsImV4cCI6MjA3NDAwODU2NH0.0f9PCFnHf_UMm2MrHXrZlZdCpnoC3NpGlw6x3BjntAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});